name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Запуск каждые 6 часов
  workflow_dispatch:       # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: maksymYena
          svg_out_path: dist/github-snake.svg

      - name: Upload snake animation as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/github-snake.svg
