name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: maksymYena
          outputs: |
            github-contribution-grid-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Create output directory
        run: mkdir -p output

      - name: Move generated files
        run: |
          mv github-contribution-grid-snake.svg output/
          mv github-snake-dark.svg output/

      - name: Push updated snake animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
