name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: maksymYena
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg || echo "No changes to commit"
          git commit -m "Updated snake animation" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/maksymYena/maksymYena.git HEAD:main
