name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: maksymYena
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push generated snake
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          mv dist/github-snake-dark.svg output/
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/
          git commit -m "Updated snake animation"
          git push
