name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Запуск каждые 6 часов
  workflow_dispatch:       # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: maksymYena
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
